[package]
name = "go"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aspen = { path = "../../aspen" }
tree-sitter-go = "0.19.1"
lazy_static = "1.0"
