[workspace]

members = [
    "marvin",           # rust types/bindings to marvin
    "globstar",         # everything you need to write lints
    "test-utils",       # annotation based test library
    "scope-resolution", # scope resolution magic
]

exclude = [
    "linters/ruby"
]

