[workspace]

members = [
    "marvin",    # rust types/bindings to marvin
    "aspen",     # everything you need to write lints
    "holly",     # annotation based test library
    "cedar",     # scope resolution magic
]

exclude = [
    "linters/ruby"
]

