[package]
name = "ruby"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aspen = { path = "../../aspen" }
tree-sitter-ruby = { git = "https://github.com/akshay-deepsource/tree-sitter-ruby" }
once_cell = "1.12.0"
