language: go
name: go_mysql_config_raw_passwd
message: "Do not hardcode MySQL passwords in the source code."
category: security
severity: critical
pattern: >
  [
    (composite_literal
  type: (qualified_type
    package: (package_identifier) @pkg
    name: (type_identifier) @type
    (#match? @pkg "^mysql$")
    (#match? @type "^Config$"))
  body: (literal_value
    (keyed_element
      (literal_element) @field
      (literal_element) @value
      (#match? @field "^Passwd$")
      (#match? @value "^\".*\"$")))) @go_mysql_config_raw_passwd
  ]
exclude:
  - "test/**"
  - "*_test.go"
  - "tests/**"
  - "__tests__/**"
description: |
  Hardcoding passwords in the source code is a security risk. Instead, consider using
  environment variables or a secure secret management service to store sensitive
  information like database passwords.