[package]
name = "scope-resolution"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies.tree-sitter]
git = "https://github.com/akshay-deepsource/tree-sitter"
