name: build-and-test
on:
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.23
      
      - name: build
        run: make build

      - name: test
        run: make testall

      - name: Report result to DeepSource
        run: |
          curl https://deepsource.io/cli | sh
          ./bin/deepsource report --analyzer test-coverage --key go --value-file ./coverage.out --use-oidc
    
